# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fcd15b09c916d3d09ab593bcaefe224288717547cd6e02e8280bec8b93d2f7c5db05aa13e2b82631ecacbf301a66f1929ac5e0512ff394a4d672ca10ea468ddc

test:
  secret_key_base: cc1d04cd2747dcb8dd36957c8cbd40dc82d9a88d815164f413978b6ee48b47a529ec21759f7f1225488dd2c63a21f4b57f943425b8d9bca21e447eb07909cf79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
